# Generated by Django 2.1.7 on 2019-03-11 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmc',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
