# Generated by Django 2.1.7 on 2019-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0002_dmc_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmc',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
