# Generated by Django 2.1.7 on 2019-03-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0004_dmc_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmc',
            old_name='auther',
            new_name='author',
        ),
    ]
