# Generated by Django 2.1.7 on 2019-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0005_auto_20190311_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmc',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dmc',
            name='readed_num',
            field=models.IntegerField(default=0),
        ),
    ]
